module.exports = [
  require('./alfabank'),
  require('./credit-agricole'),
  require('./diamant'),
  require('./kredobank'),
  require('./monobank'),
  require('./oschadbank'),
  require('./otp'),
  require('./pravex'),
  require('./privatbank'),
  require('./procredit'),
  require('./pumb'),
  require('./raiffeisen-aval'),
  require('./ukreximbank'),
  require('./ukrgasbank'),
  require('./ukrsibbank'),
  require('./ukrsotsbank'),
  require('./unicreditbank')
];
